USE SampleDB
GO

INSERT INTO City(City, [State]) VALUES('Montgomery','Alabama');
INSERT INTO City(City, [State]) VALUES('Juneau','Alaska');
INSERT INTO City(City, [State]) VALUES('Phoenix','Arizona');
INSERT INTO City(City, [State]) VALUES('Little Rock','Arkansas');
INSERT INTO City(City, [State]) VALUES('Sacramento','California');
INSERT INTO City(City, [State]) VALUES('Denver','Colorado');
INSERT INTO City(City, [State]) VALUES('Hartford','Connecticut');
INSERT INTO City(City, [State]) VALUES('Dover','Delaware');
INSERT INTO City(City, [State]) VALUES('Tallahassee','Florida');
INSERT INTO City(City, [State]) VALUES('Atlanta','Georgia');
INSERT INTO City(City, [State]) VALUES('Honolulu','Hawaii');
INSERT INTO City(City, [State]) VALUES('Boise','Idaho');
INSERT INTO City(City, [State]) VALUES('Sprinfield','Illinois');
INSERT INTO City(City, [State]) VALUES('Indianapolis','Indiana');
INSERT INTO City(City, [State]) VALUES('Des Moines','Iowa');
INSERT INTO City(City, [State]) VALUES('Topeka','Kansas');
INSERT INTO City(City, [State]) VALUES('Frankfort','Kentucky');
INSERT INTO City(City, [State]) VALUES('Baton Rouge','Louisiana');
INSERT INTO City(City, [State]) VALUES('Augusta','Maine');
INSERT INTO City(City, [State]) VALUES('Annapolis','Maryland');
INSERT INTO City(City, [State]) VALUES('Boston','Massachusetts');
INSERT INTO City(City, [State]) VALUES('Lansing','Michigan');
INSERT INTO City(City, [State]) VALUES('Saint Paul','Minnesota');
INSERT INTO City(City, [State]) VALUES('Jackson','Mississippi');
INSERT INTO City(City, [State]) VALUES('Jefferson City','Missouri');
INSERT INTO City(City, [State]) VALUES('Helena','Montana');
INSERT INTO City(City, [State]) VALUES('Lincoln','Nebraska');
INSERT INTO City(City, [State]) VALUES('Carson City','Nevada');
INSERT INTO City(City, [State]) VALUES('Concord','New Hampshire');
INSERT INTO City(City, [State]) VALUES('Trenton','New Jersey');
INSERT INTO City(City, [State]) VALUES('Santa Fe','New Mexico');
INSERT INTO City(City, [State]) VALUES('Albany','New York');
INSERT INTO City(City, [State]) VALUES('Raleigh','North Carolina');
INSERT INTO City(City, [State]) VALUES('Bismarck','North Dakota');
INSERT INTO City(City, [State]) VALUES('Columbus','Ohio');
INSERT INTO City(City, [State]) VALUES('Oklahoma City','Oklahoma');
INSERT INTO City(City, [State]) VALUES('Salem','Oregon');
INSERT INTO City(City, [State]) VALUES('Harrisburg','Pennsylvania');
INSERT INTO City(City, [State]) VALUES('Providence','Rhode Island');
INSERT INTO City(City, [State]) VALUES('Columbia','South Carolina');
INSERT INTO City(City, [State]) VALUES('Pierre','South Dakota');
INSERT INTO City(City, [State]) VALUES('Nashville','Tennessee');
INSERT INTO City(City, [State]) VALUES('Austin','Texas');
INSERT INTO City(City, [State]) VALUES('Salt Lake City','Utah');
INSERT INTO City(City, [State]) VALUES('Montpelier','Vermont');
INSERT INTO City(City, [State]) VALUES('Richmond','Virginia');
INSERT INTO City(City, [State]) VALUES('Olympia','Washington');
INSERT INTO City(City, [State]) VALUES('Charleston','West Virginia');
INSERT INTO City(City, [State]) VALUES('Madison','Wisconsin');
INSERT INTO City(City, [State]) VALUES('Cheyenne','Wyoming');