INSERT INTO [State] ([State]) VALUES ('Alabama');
INSERT INTO [State] ([State]) VALUES ('Alaska');
INSERT INTO [State] ([State]) VALUES ('Arizona');
INSERT INTO [State] ([State]) VALUES ('Arkansas');
INSERT INTO [State] ([State]) VALUES ('California');
INSERT INTO [State] ([State]) VALUES ('Colorado');
INSERT INTO [State] ([State]) VALUES ('Connecticut');
INSERT INTO [State] ([State]) VALUES ('Delaware');
INSERT INTO [State] ([State]) VALUES ('Florida');
INSERT INTO [State] ([State]) VALUES ('Georgia');
INSERT INTO [State] ([State]) VALUES ('Hawaii');
INSERT INTO [State] ([State]) VALUES ('Idaho');
INSERT INTO [State] ([State]) VALUES ('Illinois');
INSERT INTO [State] ([State]) VALUES ('Indiana');
INSERT INTO [State] ([State]) VALUES ('Iowa');
INSERT INTO [State] ([State]) VALUES ('Kansas');
INSERT INTO [State] ([State]) VALUES ('Kentucky');
INSERT INTO [State] ([State]) VALUES ('Louisiana');
INSERT INTO [State] ([State]) VALUES ('Maine');
INSERT INTO [State] ([State]) VALUES ('Maryland');
INSERT INTO [State] ([State]) VALUES ('Massachusetts');
INSERT INTO [State] ([State]) VALUES ('Michigan');
INSERT INTO [State] ([State]) VALUES ('Minnesota');
INSERT INTO [State] ([State]) VALUES ('Mississipi');
INSERT INTO [State] ([State]) VALUES ('Missouri');
INSERT INTO [State] ([State]) VALUES ('Montana');
INSERT INTO [State] ([State]) VALUES ('Nebraska');
INSERT INTO [State] ([State]) VALUES ('Nevada');
INSERT INTO [State] ([State]) VALUES ('New Hampshire');
INSERT INTO [State] ([State]) VALUES ('New Jersey');
INSERT INTO [State] ([State]) VALUES ('New Mexico');
INSERT INTO [State] ([State]) VALUES ('New York');
INSERT INTO [State] ([State]) VALUES ('North Carolina');
INSERT INTO [State] ([State]) VALUES ('North Dakota');
INSERT INTO [State] ([State]) VALUES ('Ohio');
INSERT INTO [State] ([State]) VALUES ('Oklahoma');
INSERT INTO [State] ([State]) VALUES ('Oregon');
INSERT INTO [State] ([State]) VALUES ('Pennsylvania');
INSERT INTO [State] ([State]) VALUES ('Rhode Island');
INSERT INTO [State] ([State]) VALUES ('South Carolina');
INSERT INTO [State] ([State]) VALUES ('South Dakota');
INSERT INTO [State] ([State]) VALUES ('Tennessee');
INSERT INTO [State] ([State]) VALUES ('Texas');
INSERT INTO [State] ([State]) VALUES ('Utah');
INSERT INTO [State] ([State]) VALUES ('Vermont');
INSERT INTO [State] ([State]) VALUES ('Virginia');
INSERT INTO [State] ([State]) VALUES ('Washington');
INSERT INTO [State] ([State]) VALUES ('West Virginia');
INSERT INTO [State] ([State]) VALUES ('Wisconsin');
INSERT INTO [State] ([State]) VALUES ('Wyoming');